CREATE DATABASE IF NOT EXISTS bacle_clemencon;
use bacle_clemencon;

CREATE TABLE IF NOT EXISTS web
(
    id INT NOT NULL AUTO_INCREMENT,
    uid VARCHAR(255) NOT NULL,
    url VARCHAR(1000) NOT NULL,
)

CREATE TABLE IF NOT EXISTS history
(
    id INT NOT NULL AUTO_INCREMENT,
     VARCHAR(255) NOT NULL,
    url VARCHAR(1000) NOT NULL,
)

CREATE TABLE IF NOT EXISTS user
(
    id INT NOT NULL AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL,
    pass VARCHAR(1000) NOT NULL,
)