CREATE DATABASE IF NOT EXISTS bacle_clemencon;
use bacle_clemencon;

CREATE TABLE IF NOT EXISTS user
(
    id INT NOT NULL AUTO_INCREMENT,
    mail VARCHAR(255) NOT NULL,
    pass VARCHAR(255) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS list_web
(
    id INT NOT NULL AUTO_INCREMENT,
    webUrl VARCHAR(255) NOT NULL,
    stat VARCHAR(255) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS history
(
    id INT NOT NULL AUTO_INCREMENT,
    stat VARCHAR(255) NOT NULL,
    updateStat DATETIME NOT NULL,
    PRIMARY KEY(id)
);